package views;

import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author SUSENO-PC
 */
public class menuUtama extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
        
    // waktu sekarang 
     private void setJam(){
        ActionListener listener = (ActionEvent evt) -> {
            jam.setText(new WaktuSekarang().getWkt());
        };
        new Timer(1000, listener).start();
    }
    // penutup waktu sekarang
     
    // frame maks dan geser panel
    static boolean maximixed = true;
    int xMouse;
    int yMouse;
// penutup frame maks dan geser panel
    

    
    public menuUtama() {
        initComponents();
        setJam();
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMaximize = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnMasterData = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        jPanel1 = new views.background();
        btnAbout = new javax.swing.JButton();
        jam = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        panelMasterData = new javax.swing.JPanel();
        btnDataBarang = new javax.swing.JButton();
        btnDataSupplier = new javax.swing.JButton();
        btnDataGudang = new javax.swing.JButton();
        btnDataKategori = new javax.swing.JButton();
        panelTransaksi = new javax.swing.JPanel();
        btnPenjualan = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        btnLapBarangMasuk = new javax.swing.JButton();
        btnLapBarangKeluar = new javax.swing.JButton();
        btnLapStokBarang = new javax.swing.JButton();
        btnLapDataSupplier = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelUtama.setBackground(new java.awt.Color(153, 153, 153));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUtamaMouseClicked(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(153, 153, 153));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        btnClose.setBackground(new java.awt.Color(153, 153, 153));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_4.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_5.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(102, 102, 102));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Maximize_Window_30px.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Maximize_Window_30px_1.png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseClicked(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px_1.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI WARUNG SEMBAKO RIWAYATI");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(528, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMenu.setBackground(new java.awt.Color(153, 153, 153));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelMenu.setForeground(new java.awt.Color(153, 153, 153));

        btnMasterData.setBackground(new java.awt.Color(153, 153, 153));
        btnMasterData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMasterData.setForeground(new java.awt.Color(255, 255, 255));
        btnMasterData.setText("  Master Data");
        btnMasterData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnMasterData.setContentAreaFilled(false);
        btnMasterData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasterData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMasterData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMasterData.setOpaque(true);
        btnMasterData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseExited(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(153, 153, 153));
        btnTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setText("  Transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setOpaque(true);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(153, 153, 153));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setText("  Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setOpaque(true);
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        btnAbout.setBackground(new java.awt.Color(153, 153, 153));
        btnAbout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("  About");
        btnAbout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnAbout.setContentAreaFilled(false);
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setOpaque(true);
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        jam.setBackground(new java.awt.Color(153, 153, 153));
        jam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jam.setForeground(new java.awt.Color(255, 255, 255));
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jam.setOpaque(true);

        tgl.setBackground(new java.awt.Color(153, 153, 153));
        tgl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgl.setOpaque(true);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMasterData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jam.setText(new WaktuSekarang().getWkt());
        jam.setPreferredSize(new java.awt.Dimension(100,22));
        tgl.setText(new WaktuSekarang().getTgl());
        tgl.setPreferredSize(new java.awt.Dimension(120,22));

        panelMasterData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnDataBarang.setBackground(new java.awt.Color(0, 0, 204));
        btnDataBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDataBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnDataBarang.setText("  > Data Barang");
        btnDataBarang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDataBarang.setContentAreaFilled(false);
        btnDataBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDataBarang.setOpaque(true);
        btnDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataBarangMouseExited(evt);
            }
        });
        btnDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBarangActionPerformed(evt);
            }
        });

        btnDataSupplier.setBackground(new java.awt.Color(0, 0, 204));
        btnDataSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDataSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnDataSupplier.setText("  > Data User");
        btnDataSupplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDataSupplier.setContentAreaFilled(false);
        btnDataSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDataSupplier.setOpaque(true);
        btnDataSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataSupplierMouseExited(evt);
            }
        });
        btnDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSupplierActionPerformed(evt);
            }
        });

        btnDataGudang.setBackground(new java.awt.Color(0, 0, 204));
        btnDataGudang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDataGudang.setForeground(new java.awt.Color(255, 255, 255));
        btnDataGudang.setText("  > Data Gudang");
        btnDataGudang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDataGudang.setContentAreaFilled(false);
        btnDataGudang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataGudang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataGudang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDataGudang.setOpaque(true);
        btnDataGudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataGudangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataGudangMouseExited(evt);
            }
        });
        btnDataGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataGudangActionPerformed(evt);
            }
        });

        btnDataKategori.setBackground(new java.awt.Color(0, 0, 204));
        btnDataKategori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDataKategori.setForeground(new java.awt.Color(255, 255, 255));
        btnDataKategori.setText("  > Data Kategori");
        btnDataKategori.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDataKategori.setContentAreaFilled(false);
        btnDataKategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataKategori.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataKategori.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDataKategori.setOpaque(true);
        btnDataKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataKategoriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataKategoriMouseExited(evt);
            }
        });
        btnDataKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMasterDataLayout = new javax.swing.GroupLayout(panelMasterData);
        panelMasterData.setLayout(panelMasterDataLayout);
        panelMasterDataLayout.setHorizontalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnDataSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnDataGudang, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnDataKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelMasterDataLayout.setVerticalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasterDataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDataSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDataGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDataKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPenjualan.setBackground(new java.awt.Color(0, 0, 204));
        btnPenjualan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnPenjualan.setText("> Tranksaksi Penjualan");
        btnPenjualan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPenjualan.setContentAreaFilled(false);
        btnPenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPenjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPenjualan.setOpaque(true);
        btnPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPenjualanMouseExited(evt);
            }
        });
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });

        btnStok.setBackground(new java.awt.Color(0, 0, 204));
        btnStok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStok.setForeground(new java.awt.Color(255, 255, 255));
        btnStok.setText("> Riwayat Tranksaksi");
        btnStok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStok.setContentAreaFilled(false);
        btnStok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStok.setOpaque(true);
        btnStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStokMouseExited(evt);
            }
        });
        btnStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStok, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addComponent(btnPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLapBarangMasuk.setBackground(new java.awt.Color(0, 0, 204));
        btnLapBarangMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapBarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnLapBarangMasuk.setText("  > Laporan Barang Masuk");
        btnLapBarangMasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapBarangMasuk.setContentAreaFilled(false);
        btnLapBarangMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapBarangMasuk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapBarangMasuk.setOpaque(true);
        btnLapBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapBarangMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapBarangMasukMouseExited(evt);
            }
        });
        btnLapBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapBarangMasukActionPerformed(evt);
            }
        });

        btnLapBarangKeluar.setBackground(new java.awt.Color(0, 0, 204));
        btnLapBarangKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapBarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnLapBarangKeluar.setText("  > Laporan Barang Keluar");
        btnLapBarangKeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapBarangKeluar.setContentAreaFilled(false);
        btnLapBarangKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapBarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapBarangKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapBarangKeluar.setOpaque(true);
        btnLapBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapBarangKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapBarangKeluarMouseExited(evt);
            }
        });
        btnLapBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapBarangKeluarActionPerformed(evt);
            }
        });

        btnLapStokBarang.setBackground(new java.awt.Color(0, 0, 204));
        btnLapStokBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapStokBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnLapStokBarang.setText("  > Laporan Stok Barang");
        btnLapStokBarang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapStokBarang.setContentAreaFilled(false);
        btnLapStokBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapStokBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapStokBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapStokBarang.setOpaque(true);
        btnLapStokBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapStokBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapStokBarangMouseExited(evt);
            }
        });
        btnLapStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapStokBarangActionPerformed(evt);
            }
        });

        btnLapDataSupplier.setBackground(new java.awt.Color(0, 0, 204));
        btnLapDataSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapDataSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnLapDataSupplier.setText("  > Laporan Data Supplier");
        btnLapDataSupplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapDataSupplier.setContentAreaFilled(false);
        btnLapDataSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapDataSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapDataSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapDataSupplier.setOpaque(true);
        btnLapDataSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapDataSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapDataSupplierMouseExited(evt);
            }
        });
        btnLapDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapDataSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLapBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapBarangMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapStokBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapDataSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addComponent(btnLapBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapDataSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiqih Ramdhani\\Downloads\\Programs\\App silent\\src\\images\\mark-olsen-bZQSR0Ilq-8-unsplash.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        String ObjButton[] = {"YES","NO"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda yakin ingi keluar?","Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null,ObjButton,ObjButton[1]);
        if(pilihan == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMasterDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseClicked
        panelMasterData.setVisible(true);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnMasterDataMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        panelTransaksi.setVisible(true);
        panelMasterData.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        panelLaporan.setVisible(true);
        panelTransaksi.setVisible(false);
        panelMasterData.setVisible(false);
    }//GEN-LAST:event_btnLaporanMouseClicked

     @SuppressWarnings("deprecation")
    private void btnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBarangActionPerformed
        panelMasterData.setVisible(false);
        new dataBarang(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnDataBarangActionPerformed

    private void panelUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseClicked
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_panelUtamaMouseClicked

    private void btnMasterDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseEntered
        btnMasterData.setForeground(Color.white);
        btnMasterData.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnMasterDataMouseEntered

    private void btnMasterDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseExited
        btnMasterData.setForeground(Color.white);
        btnMasterData.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnMasterDataMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        btnTransaksi.setForeground(Color.white);
        btnTransaksi.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        btnTransaksi.setForeground(Color.white);
        btnTransaksi.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        btnLaporan.setForeground(Color.white);
        btnLaporan.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        btnLaporan.setForeground(Color.white);
        btnLaporan.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btnDataBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataBarangMouseEntered
        btnDataBarang.setForeground(Color.red);
        btnDataBarang.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnDataBarangMouseEntered

    private void btnDataBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataBarangMouseExited
        btnDataBarang.setForeground(Color.white);
        btnDataBarang.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnDataBarangMouseExited

    private void btnDataSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataSupplierMouseEntered
        btnDataSupplier.setForeground(Color.red);
        btnDataSupplier.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnDataSupplierMouseEntered

    private void btnDataSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataSupplierMouseExited
        btnDataSupplier.setForeground(Color.white);
        btnDataSupplier.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnDataSupplierMouseExited

    private void btnDataGudangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataGudangMouseEntered
        btnDataGudang.setForeground(Color.red);
        btnDataGudang.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnDataGudangMouseEntered

    private void btnDataGudangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataGudangMouseExited
        btnDataGudang.setForeground(Color.white);
        btnDataGudang.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnDataGudangMouseExited

    private void btnDataKategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKategoriMouseEntered
        btnDataKategori.setForeground(Color.red);
        btnDataKategori.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnDataKategoriMouseEntered

    private void btnDataKategoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKategoriMouseExited
        btnDataKategori.setForeground(Color.white);
        btnDataKategori.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnDataKategoriMouseExited

    private void btnPenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenjualanMouseEntered
        btnPenjualan.setForeground(Color.red);
        btnPenjualan.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnPenjualanMouseEntered

    private void btnPenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenjualanMouseExited
        btnPenjualan.setForeground(Color.white);
        btnPenjualan.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnPenjualanMouseExited

    private void btnStokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStokMouseEntered
        btnStok.setForeground(Color.red);
        btnStok.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnStokMouseEntered

    private void btnStokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStokMouseExited
        btnStok.setForeground(Color.white);
        btnStok.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnStokMouseExited

    private void btnLapBarangMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapBarangMasukMouseEntered
        btnLapBarangMasuk.setForeground(Color.red);
        btnLapBarangMasuk.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnLapBarangMasukMouseEntered

    private void btnLapBarangMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapBarangMasukMouseExited
        btnLapBarangMasuk.setForeground(Color.white);
        btnLapBarangMasuk.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnLapBarangMasukMouseExited

    private void btnLapBarangKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapBarangKeluarMouseEntered
        btnLapBarangKeluar.setForeground(Color.red);
        btnLapBarangKeluar.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnLapBarangKeluarMouseEntered

    private void btnLapBarangKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapBarangKeluarMouseExited
        btnLapBarangKeluar.setForeground(Color.white);
        btnLapBarangKeluar.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnLapBarangKeluarMouseExited

    private void btnLapStokBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapStokBarangMouseEntered
        btnLapStokBarang.setForeground(Color.red);
        btnLapStokBarang.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnLapStokBarangMouseEntered

    private void btnLapStokBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapStokBarangMouseExited
        btnLapStokBarang.setForeground(Color.white);
        btnLapStokBarang.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnLapStokBarangMouseExited

     @SuppressWarnings("deprecation")
    private void btnDataKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKategoriActionPerformed
        panelMasterData.setVisible(false);
        new dataKategori(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnDataKategoriActionPerformed

    private void btnMaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseClicked
        if(maximixed){
            menuUtama.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            menuUtama.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximixed = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximixed = true;
        }
    }//GEN-LAST:event_btnMaximizeMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

     @SuppressWarnings("deprecation")
    private void btnDataGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataGudangActionPerformed
        panelMasterData.setVisible(false);
        new dataGudang(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnDataGudangActionPerformed

     @SuppressWarnings("deprecation")
    private void btnDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplierActionPerformed
        panelMasterData.setVisible(false);
        new dataUser(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnDataSupplierActionPerformed

     @SuppressWarnings("deprecation")
    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
         panelTransaksi.setVisible(false);
         new Penjualan().setVisible(true);
         Penjualan.setDefaultLookAndFeelDecorated(true);
    }//GEN-LAST:event_btnPenjualanActionPerformed

    @SuppressWarnings({"deprecation"})
    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        panelTransaksi.setVisible(false);
        new Riwayat().setVisible(true);
        Riwayat.setDefaultLookAndFeelDecorated(true);
    }//GEN-LAST:event_btnStokActionPerformed

    private void btnLapBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapBarangMasukActionPerformed
    
    }//GEN-LAST:event_btnLapBarangMasukActionPerformed

    private void btnLapBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapBarangKeluarActionPerformed
        
    }//GEN-LAST:event_btnLapBarangKeluarActionPerformed

    private void btnLapStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapStokBarangActionPerformed
      
    }//GEN-LAST:event_btnLapStokBarangActionPerformed

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        btnAbout.setForeground(Color.WHITE);
        btnAbout.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        btnAbout.setForeground(Color.white);
        btnAbout.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnAboutMouseExited

    @SuppressWarnings("deprecation")
    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        new about(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnLapDataSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDataSupplierMouseEntered
        btnLapDataSupplier.setForeground(Color.red);
        btnLapDataSupplier.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_btnLapDataSupplierMouseEntered

    private void btnLapDataSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDataSupplierMouseExited
        btnLapDataSupplier.setForeground(Color.white);
        btnLapDataSupplier.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_btnLapDataSupplierMouseExited

    private void btnLapDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapDataSupplierActionPerformed
      
    }//GEN-LAST:event_btnLapDataSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            menuUtama mn = new menuUtama();
            mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
            mn.setVisible(true);           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDataBarang;
    private javax.swing.JButton btnDataGudang;
    private javax.swing.JButton btnDataKategori;
    private javax.swing.JButton btnDataSupplier;
    private javax.swing.JButton btnLapBarangKeluar;
    private javax.swing.JButton btnLapBarangMasuk;
    private javax.swing.JButton btnLapDataSupplier;
    private javax.swing.JButton btnLapStokBarang;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMasterData;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jam;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelMasterData;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}

